
  - name: enable mysql
    ansible.builtin.dnf: 
      name: mysql-server
      state: present

  - name:  start and enable mysql server
    ansible.builtin.service: 
      name: mysqld
      state: restarted
      enabled: yes

  - name: creating root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"


       
