- name: resatrt nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf.j2
    notify: resatrt nginx