- name: task-1
  ansible.builtin.debug:
    msg: "Hi, from Task-1"

- name: task-2
  ansible.builtin.debbug:
    msg: "Hi, from Task-2"

- name: task-3
  ansible.builtin.debug:
    msg: "Hi, from Task-3"