- name: copy {{ component }} service
  ansible.builtin.copy:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: demon reload systemd_service
  ansible.builtin.systemd_service:
    daemon_reload: true